version: '3.4'

networks:
  banknoteauthentication:
    external: false

services:
  jupyter:
    build: ./jupyter
    container_name: banknoteauthentication_jupyter
    restart: always
    networks:
      - banknoteauthentication
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/data:/home/jovyan/data
      - ./jupyter/notebooks:/home/jovyan/notebooks